import { useMemo } from "react";
import {
  createWorkbenchConnectionRestoreActions,
  type WorkbenchConnectionRestoreActions,
} from "./workbench-session-restore-runner";

export function useWorkbenchConnectionRestoreActions(
  input: WorkbenchConnectionRestoreActions,
) {
  return useMemo(
    () => createWorkbenchConnectionRestoreActions(input),
    [
      input.setActiveSchema,
      input.setActiveTabId,
      input.setApplyExecute,
      input.setApplyJobDetail,
      input.setApplyPreview,
      input.setApplyProdConfirmation,
      input.setApplyUnsafeDeleteConfirmed,
      input.setDiffDetail,
      input.setDiffPreview,
      input.setDiffRows,
      input.setInspectionState,
      input.setLastGridEditSource,
      input.setParameterValues,
      input.setPendingDeleteRows,
      input.setPendingEditCells,
      input.setPendingInsertedRows,
      input.setPendingParameterReview,
      input.setPendingScriptReview,
      input.setPreparedGridPlan,
      input.setQueryHistory,
      input.setRecentQueries,
      input.setRestoredInspectionTarget,
      input.setResultTab,
      input.setSavedSnippets,
      input.setSchemaDiffTargetConnectionId,
      input.setSelectedDiffRowIndex,
      input.setSelectedJobId,
      input.setSelectedSqlLibraryEntryId,
      input.setSelectedTableName,
      input.setSqlCopilotGeneratedDraft,
      input.setSqlCopilotGenerationError,
      input.setSqlCopilotOpen,
      input.setSqlCopilotOperatorPrompt,
      input.setSqlCopilotProbeError,
      input.setSqlCopilotProbeResult,
      input.setSqlLibraryOpen,
      input.setSqlLibrarySearch,
      input.setSqlMemory,
      input.setSqlMemoryOpen,
      input.setSyncIncludeUnchanged,
      input.setSyncIssue,
      input.setSyncSelectedTables,
      input.setSyncSourceConnectionId,
      input.setSyncTargetConnectionId,
      input.setTabs,
    ],
  );
}
