import { useMemo } from "react";
import type { UseWorkbenchStateActionRegistriesInput } from "./use-workbench-state-action-registries";

export function useWorkbenchStateActionRegistryInput(
  input: UseWorkbenchStateActionRegistriesInput,
): UseWorkbenchStateActionRegistriesInput {
  return useMemo(
    () => ({
      ...input,
      clearShownWindowCapNotices: input.clearShownWindowCapNotices,
    }),
    [
      input.activeExportRequestIdRef,
      input.activeQueryRequestIdRef,
      input.clearShownWindowCapNotices,
      input.queryClient,
      input.showNotification,
      input.setActiveBatchIndex,
      input.setApplyExecute,
      input.setApplyJobDetail,
      input.setApplyPreview,
      input.setApplyProdConfirmation,
      input.setApplyUnsafeDeleteConfirmed,
      input.setBackgroundJobs,
      input.setCurrentExportRequestId,
      input.setCurrentRequestId,
      input.setDangerPreview,
      input.setDiffDetail,
      input.setDiffPreview,
      input.setDiffRows,
      input.setExplainError,
      input.setExplainPlan,
      input.setInspectionState,
      input.setIsApplyPreviewing,
      input.setIsCommittingGridEdit,
      input.setIsDiffPreviewing,
      input.setIsExecuting,
      input.setIsExecutingApply,
      input.setIsExplaining,
      input.setIsExporting,
      input.setIsGeneratingSqlCopilotDraft,
      input.setIsInspectingObject,
      input.setIsPreparingGridCommit,
      input.setIsRefreshingJobs,
      input.setIsRunningSqlCopilotProbe,
      input.setIsSavingSqlCopilotSettings,
      input.setIsSchemaDiffing,
      input.setJobCenterIssue,
      input.setLastGridEditSource,
      input.setParameterValues,
      input.setPendingCursorOffset,
      input.setPendingDeleteRows,
      input.setPendingEditCells,
      input.setPendingInsertedRows,
      input.setPendingParameterReview,
      input.setPendingQueryMode,
      input.setPendingQuerySource,
      input.setPendingScriptReview,
      input.setPendingSnippetName,
      input.setPendingSql,
      input.setPreparedGridPlan,
      input.setQueryError,
      input.setQueryHistory,
      input.setRecentQueries,
      input.setRestoredInspectionTarget,
      input.setResultTab,
      input.setResults,
      input.setSaveSnippetDialogOpen,
      input.setSavedSnippets,
      input.setSchemaDiffState,
      input.setSchemaDiffTargetConnectionId,
      input.setSelectedDiffRowIndex,
      input.setSelectedJobId,
      input.setSelectedSqlLibraryEntryId,
      input.setSelectedTableName,
      input.setShowDangerDialog,
      input.setSqlCopilotGeneratedDraft,
      input.setSqlCopilotGenerationError,
      input.setSqlCopilotOpen,
      input.setSqlCopilotProbeError,
      input.setSqlCopilotProbeResult,
      input.setSqlCopilotSettingsDraft,
      input.setSqlLibraryOpen,
      input.setSqlLibrarySearch,
      input.setSqlMemory,
      input.setSqlMemoryOpen,
      input.setSyncIncludeUnchanged,
      input.setSyncIssue,
      input.setSyncSelectedTables,
      input.setSyncSourceConnectionId,
      input.setSyncTableConfigs,
      input.setSyncTargetConnectionId,
    ],
  );
}
