DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'dbtools_readonly') THEN
    CREATE ROLE dbtools_readonly LOGIN PASSWORD 'dbtools_readonly';
  END IF;
END
$$;

CREATE SCHEMA IF NOT EXISTS app AUTHORIZATION dbtools_writable;

CREATE TABLE IF NOT EXISTS app.departments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code VARCHAR(32) NOT NULL,
  name VARCHAR(120) NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT uq_departments_code UNIQUE (code)
);

COMMENT ON TABLE app.departments IS 'DBTools lab department master';
COMMENT ON COLUMN app.departments.code IS 'Enterprise department code';

CREATE TABLE IF NOT EXISTS app.employees (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  department_id BIGINT NOT NULL,
  employee_no VARCHAR(32) NOT NULL,
  full_name VARCHAR(160) NOT NULL,
  status VARCHAR(24) NOT NULL DEFAULT 'active',
  hired_on DATE,
  salary NUMERIC(12,2),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT uq_employees_employee_no UNIQUE (employee_no),
  CONSTRAINT fk_employees_department
    FOREIGN KEY (department_id) REFERENCES app.departments(id)
);

COMMENT ON TABLE app.employees IS 'DBTools lab employee transaction table';
COMMENT ON COLUMN app.employees.employee_no IS 'Enterprise employee number';

CREATE INDEX IF NOT EXISTS idx_employees_department_status
  ON app.employees (department_id, status);

CREATE TABLE IF NOT EXISTS app.schema_change_audit (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  object_name VARCHAR(160) NOT NULL,
  action VARCHAR(32) NOT NULL,
  note TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE OR REPLACE VIEW app.active_employees AS
SELECT
  e.id,
  e.employee_no,
  e.full_name,
  d.code AS department_code,
  d.name AS department_name
FROM app.employees e
JOIN app.departments d ON d.id = e.department_id
WHERE e.status = 'active';

CREATE OR REPLACE FUNCTION app.count_active_employees()
RETURNS BIGINT
LANGUAGE sql
STABLE
AS $$
  SELECT COUNT(*) FROM app.employees WHERE status = 'active';
$$;

INSERT INTO app.departments (id, code, name) VALUES
  (1, 'ENG', 'Engineering'),
  (2, 'OPS', 'Operations'),
  (3, 'FIN', 'Finance')
ON CONFLICT (id) DO NOTHING;

INSERT INTO app.employees (id, department_id, employee_no, full_name, status, hired_on, salary) VALUES
  (1, 1, 'E-1001', 'Aki Tanaka', 'active', '2024-04-01', 82000.00),
  (2, 1, 'E-1002', 'Mina Sato', 'active', '2024-06-15', 79000.00),
  (3, 2, 'E-2001', 'Ken Mori', 'inactive', '2023-11-20', 68000.00),
  (4, 3, 'E-3001', 'Yui Kato', 'active', '2025-01-10', 73000.00)
ON CONFLICT (id) DO NOTHING;

SELECT setval('app.departments_id_seq', GREATEST((SELECT MAX(id) FROM app.departments), 1));
SELECT setval('app.employees_id_seq', GREATEST((SELECT MAX(id) FROM app.employees), 1));

GRANT CONNECT ON DATABASE dbtools_lab TO dbtools_readonly;
GRANT USAGE ON SCHEMA app TO dbtools_readonly;
GRANT SELECT ON ALL TABLES IN SCHEMA app TO dbtools_readonly;
ALTER DEFAULT PRIVILEGES IN SCHEMA app GRANT SELECT ON TABLES TO dbtools_readonly;
