// Live data-layer verification against a real MySQL/MariaDB engine.
//
// This does NOT drive the GUI (headless box). It proves the project's actual
// SQL-generation code produces engine-valid SQL and that the
// introspect -> design -> ALTER -> re-introspect loop works on a real database:
//   1. buildCreateTableDdl  -> CREATE a table, executed live
//   2. introspect the live table from information_schema (real shape)
//   3. diffTableDraft(introspected, edited) -> ALTER, executed live
//   4. re-introspect and assert the live columns match the edited design
//   5. buildInsertScript -> INSERT rows, executed live, row count confirmed
//
// Usage: MYSQL_EXE=...\mysql.exe DB_PORT=3306 node --import=tsx script/db-live-verify.ts

import { execFileSync } from "node:child_process";
import {
  buildCreateTableDdl,
  diffTableDraft,
  emptyTableDraftColumn,
  tableDesignChangesToScript,
  tableDraftFromSchema,
  type TableDraft,
} from "../client/src/components/extensions/db-workbench/table-designer-model";
import { buildInsertScript } from "../client/src/components/extensions/db-workbench/result-sql-export";
import { buildCsvImportPlan } from "../client/src/components/extensions/db-workbench/csv-import-model";
import {
  buildDropTableSql,
  buildDuplicateTableStructureSql,
  buildRenameTableSql,
  buildTruncateTableSql,
} from "../client/src/components/extensions/db-workbench/table-operations-model";
import { buildCsvExport } from "../client/src/components/extensions/db-workbench/result-data-export";
import { buildTableSqlDump } from "../client/src/components/extensions/db-workbench/table-sql-dump-model";
import type { DbColumnSchema, DbTableSchema } from "../shared/schema";

const MYSQL_EXE = process.env.MYSQL_EXE;
const HOST = process.env.DB_HOST ?? "127.0.0.1";
const PORT = process.env.DB_PORT ?? "3306";
const USER = process.env.DB_USER ?? "root";
const PASSWORD = process.env.DB_PASSWORD ?? "";
const DB = "dbtools_lab";

if (!MYSQL_EXE) {
  console.error("MYSQL_EXE env var (path to mysql.exe) is required.");
  process.exit(2);
}

function mysql(sql: string, opts: { db?: boolean; batch?: boolean } = {}): string {
  const args = ["-h", HOST, "-P", PORT, "-u", USER, "--protocol=tcp"];
  if (PASSWORD) args.push(`-p${PASSWORD}`);
  if (opts.batch) args.push("--batch", "--skip-column-names");
  if (opts.db) args.push(DB);
  args.push("-e", sql);
  return execFileSync(MYSQL_EXE as string, args, { encoding: "utf8" });
}

function introspectTable(table: string): DbTableSchema {
  const colRows = mysql(
    `SELECT column_name, column_type, is_nullable, column_key, column_default, column_comment
     FROM information_schema.columns
     WHERE table_schema='${DB}' AND table_name='${table}'
     ORDER BY ordinal_position;`,
    { db: false, batch: true },
  ).trim();

  const columns: DbColumnSchema[] = colRows
    .split(/\r?\n/)
    .filter(Boolean)
    .map((line) => {
      const [name, type, isNullable, key, def, comment] = line.split("\t");
      return {
        name: name!,
        dataType: type!,
        nullable: isNullable === "YES",
        primaryKey: key === "PRI",
        defaultValue: def && def !== "NULL" ? def : undefined,
        comment: comment || undefined,
      };
    });

  return { name: table, columns };
}

const results: { step: string; ok: boolean; detail?: string }[] = [];
function record(step: string, ok: boolean, detail?: string) {
  results.push({ step, ok, detail });
  console.log(`${ok ? "PASS" : "FAIL"}  ${step}${detail ? `  -- ${detail}` : ""}`);
}

try {
  mysql(`CREATE DATABASE IF NOT EXISTS \`${DB}\`;`, { db: false });
  mysql(`DROP TABLE IF EXISTS \`users\`;`, { db: true });

  // 1. CREATE from a designer draft (project code).
  const newDraft: TableDraft = {
    name: "users",
    comment: "app users",
    columns: [
      { id: "c1", name: "id", dataType: "int", nullable: false, primaryKey: true, autoIncrement: true },
      { id: "c2", name: "email", dataType: "varchar(255)", nullable: false, primaryKey: false },
      { id: "c3", name: "nickname", dataType: "varchar(64)", nullable: true, primaryKey: false, comment: "display name" },
    ],
  };
  const createSql = buildCreateTableDdl(newDraft, "mysql");
  mysql(createSql, { db: true });
  record("CREATE TABLE generated by buildCreateTableDdl executes", true);

  // 2. Introspect the real table.
  const introspected = introspectTable("users");
  record(
    "introspect users from information_schema",
    introspected.columns.length === 3,
    `${introspected.columns.length} columns`,
  );

  // 3. Edit the introspected shape and apply the generated ALTER diff.
  const editDraft = tableDraftFromSchema(introspected);
  const nickname = editDraft.columns.find((c) => c.originalName === "nickname");
  if (nickname) nickname.name = "display_name";
  const createdAt = emptyTableDraftColumn();
  createdAt.name = "created_at";
  createdAt.dataType = "datetime";
  createdAt.nullable = false;
  createdAt.defaultValue = "CURRENT_TIMESTAMP";
  editDraft.columns.push(createdAt);

  const alterSql = tableDesignChangesToScript(
    diffTableDraft(introspected, editDraft, "mysql"),
  );
  for (const stmt of alterSql.split(/;\s*\n?/).map((s) => s.trim()).filter(Boolean)) {
    mysql(`${stmt};`, { db: true });
  }
  record("ALTER diff generated by diffTableDraft executes", true);

  // 4. Re-introspect and confirm the edits took effect.
  const after = introspectTable("users");
  const names = after.columns.map((c) => c.name).sort();
  const hasRename = names.includes("display_name") && !names.includes("nickname");
  const hasAdd = names.includes("created_at");
  record(
    "re-introspect reflects rename + added column",
    hasRename && hasAdd,
    names.join(","),
  );

  // 5. INSERT export script executes and rows land.
  const insertSql = buildInsertScript({
    driver: "mysql",
    tableName: "users",
    columns: [{ name: "email" }, { name: "display_name" }],
    rows: [
      ["a@example.com", "Alice"],
      ["b@example.com", "Bob's \"acct\""],
    ],
  });
  mysql(insertSql, { db: true });
  const count = mysql(`SELECT COUNT(*) FROM \`users\`;`, { db: true, batch: true }).trim();
  record("buildInsertScript executes and rows land", count === "2", `count=${count}`);

  // 6. CSV import: infer types, CREATE + INSERT from CSV, executed live.
  mysql(`DROP TABLE IF EXISTS \`imported\`;`, { db: true });
  const importPlan = buildCsvImportPlan(
    "id,amount,label\n1,9.99,alpha\n2,19.50,\"beta, gamma\"\n3,,delta\n",
    { driver: "mysql", tableName: "imported", createTable: true },
  );
  if (importPlan.createDdl) mysql(importPlan.createDdl, { db: true });
  mysql(importPlan.insertScript, { db: true });
  const importedCount = mysql(`SELECT COUNT(*) FROM \`imported\`;`, {
    db: true,
    batch: true,
  }).trim();
  // The blank amount on row 3 must be NULL, and the int id must be a real number.
  const nullAmounts = mysql(
    `SELECT COUNT(*) FROM \`imported\` WHERE amount IS NULL;`,
    { db: true, batch: true },
  ).trim();
  const idType = mysql(
    `SELECT data_type FROM information_schema.columns
     WHERE table_schema='${DB}' AND table_name='imported' AND column_name='id';`,
    { db: false, batch: true },
  ).trim();
  record(
    "buildCsvImportPlan CREATE+INSERT executes with inferred types and NULL blanks",
    importedCount === "3" && nullAmounts === "1" && idType === "int",
    `rows=${importedCount} nullAmounts=${nullAmounts} idType=${idType}`,
  );

  // 7. Table operations: duplicate structure -> rename -> truncate -> drop.
  const tableExists = (name: string) =>
    mysql(
      `SELECT COUNT(*) FROM information_schema.tables
       WHERE table_schema='${DB}' AND table_name='${name}';`,
      { db: false, batch: true },
    ).trim();

  mysql(`DROP TABLE IF EXISTS \`imported_copy\`, \`imported_renamed\`;`, { db: true });
  mysql(buildDuplicateTableStructureSql("imported", "imported_copy", "mysql"), { db: true });
  mysql(buildRenameTableSql("imported_copy", "imported_renamed", "mysql"), { db: true });
  mysql(buildTruncateTableSql("imported_renamed", "mysql"), { db: true });
  const renamedRows = mysql(`SELECT COUNT(*) FROM \`imported_renamed\`;`, {
    db: true,
    batch: true,
  }).trim();
  mysql(buildDropTableSql("imported_renamed", "mysql", { ifExists: true }), { db: true });
  const opsOk =
    tableExists("imported_copy") === "0" && // renamed away
    tableExists("imported_renamed") === "0" && // dropped
    renamedRows === "0"; // truncated before drop
  record(
    "table ops (duplicate -> rename -> truncate -> drop) execute live",
    opsOk,
    `renamedRowsAfterTruncate=${renamedRows}`,
  );

  // 8. Export -> import round trip: CSV-export rows, re-import them live, read
  // back and confirm the tricky value survived intact.
  mysql(`DROP TABLE IF EXISTS \`roundtrip\`;`, { db: true });
  const exportColumns = [{ name: "id" }, { name: "label" }];
  const exportRows: (string | number | null)[][] = [
    [1, "comma, and \"quote\""],
    [2, null],
  ];
  const csvText = buildCsvExport(exportColumns, exportRows);
  const roundtripPlan = buildCsvImportPlan(csvText, {
    driver: "mysql",
    tableName: "roundtrip",
    createTable: true,
  });
  if (roundtripPlan.createDdl) mysql(roundtripPlan.createDdl, { db: true });
  mysql(roundtripPlan.insertScript, { db: true });
  const recovered = mysql(
    `SELECT label FROM \`roundtrip\` WHERE id=1;`,
    { db: true, batch: true },
  ).trim();
  const rtCount = mysql(`SELECT COUNT(*) FROM \`roundtrip\`;`, {
    db: true,
    batch: true,
  }).trim();
  record(
    "CSV export -> import round trip preserves data live",
    rtCount === "2" && recovered === 'comma, and "quote"',
    `count=${rtCount} recovered=${JSON.stringify(recovered)}`,
  );

  // 9. Full-table SQL dump is an idempotent restore script: running it twice
  // leaves exactly the dumped rows (DROP + CREATE + INSERT).
  mysql(`DROP TABLE IF EXISTS \`dumped\`;`, { db: true });
  const dumpSchema: DbTableSchema = {
    name: "dumped",
    columns: [
      { name: "id", dataType: "int", nullable: false, primaryKey: true },
      { name: "email", dataType: "varchar(255)", nullable: false, primaryKey: false },
    ],
  };
  const dumpRows: (string | number | null)[][] = [
    [1, "a@example.com"],
    [2, "b@example.com"],
  ];
  const dumpSql = buildTableSqlDump(dumpSchema, dumpRows, { driver: "mysql" });
  const runDump = () => {
    for (const stmt of dumpSql.split(/;\s*\n/).map((s) => s.trim()).filter(Boolean)) {
      mysql(`${stmt.replace(/;$/, "")};`, { db: true });
    }
  };
  runDump();
  runDump(); // idempotent restore
  const dumpedCount = mysql(`SELECT COUNT(*) FROM \`dumped\`;`, {
    db: true,
    batch: true,
  }).trim();
  record(
    "full-table SQL dump restores idempotently (run twice -> exact rows)",
    dumpedCount === "2",
    `count=${dumpedCount}`,
  );
} catch (error) {
  record("live verification", false, String(error instanceof Error ? error.message : error));
}

const failed = results.filter((r) => !r.ok);
console.log(`\n${results.length - failed.length}/${results.length} live checks passed`);
process.exit(failed.length === 0 ? 0 : 1);
