export const APP_DEFAULTS = {
  excel: {
    pkMarkers: ["\u3007"],
    maxFileSizeMb: 50,
    maxRowsPerSheet: 100_000,
    maxConsecutiveEmptyRows: 10,
  },
  rateLimit: {
    uploadWindowMs: 60_000,
    uploadMaxRequests: 20,
    parseWindowMs: 60_000,
    parseMaxRequests: 40,
    globalProtectWindowMs: 60_000,
    globalProtectMaxRequests: 240,
    globalProtectMaxInFlight: 80,
  },
  prewarm: {
    enabled: true,
    maxConcurrency: 1,
    queueMax: 12,
    maxFileMb: 20,
  },
  taskManager: {
    maxQueueLength: 200,
    stalePendingMs: 30 * 60 * 1000,
  },
  nameFix: {
    defaultMode: "copy",
    conflictStrategy: "suffix_increment",
    reservedWordStrategy: "prefix",
    lengthOverflowStrategy: "truncate_hash",
    maxIdentifierLength: 64,
    backupRetentionDays: 30,
    maxBatchConcurrency: 4,
    allowOverwriteInElectron: true,
    allowExternalPathWrite: false,
  },
} as const;

export const DEFAULT_DDL_SETTINGS_VALUES = {
  mysqlEngine: "InnoDB",
  mysqlCharset: "utf8mb4",
  mysqlCollate: "utf8mb4_bin",
  varcharCharset: "utf8mb4",
  varcharCollate: "utf8mb4_bin",
  exportFilenamePrefix: "Crt_",
  exportFilenameSuffix: "",
  includeCommentHeader: true,
  authorName: "ISI",
  includeSetNames: true,
  includeDropTable: true,
  mysqlDataTypeCase: "lower",
  mysqlBooleanMode: "tinyint(1)",
  useCustomHeader: false,
  pkMarkers: APP_DEFAULTS.excel.pkMarkers,
  maxConsecutiveEmptyRows: APP_DEFAULTS.excel.maxConsecutiveEmptyRows,
  uploadRateLimitWindowMs: APP_DEFAULTS.rateLimit.uploadWindowMs,
  uploadRateLimitMaxRequests: APP_DEFAULTS.rateLimit.uploadMaxRequests,
  parseRateLimitWindowMs: APP_DEFAULTS.rateLimit.parseWindowMs,
  parseRateLimitMaxRequests: APP_DEFAULTS.rateLimit.parseMaxRequests,
  globalProtectRateLimitWindowMs: APP_DEFAULTS.rateLimit.globalProtectWindowMs,
  globalProtectRateLimitMaxRequests: APP_DEFAULTS.rateLimit.globalProtectMaxRequests,
  globalProtectMaxInFlight: APP_DEFAULTS.rateLimit.globalProtectMaxInFlight,
  prewarmEnabled: APP_DEFAULTS.prewarm.enabled,
  prewarmMaxConcurrency: APP_DEFAULTS.prewarm.maxConcurrency,
  prewarmQueueMax: APP_DEFAULTS.prewarm.queueMax,
  prewarmMaxFileMb: APP_DEFAULTS.prewarm.maxFileMb,
  taskManagerMaxQueueLength: APP_DEFAULTS.taskManager.maxQueueLength,
  taskManagerStalePendingMs: APP_DEFAULTS.taskManager.stalePendingMs,
  nameFixDefaultMode: APP_DEFAULTS.nameFix.defaultMode,
  nameFixConflictStrategy: APP_DEFAULTS.nameFix.conflictStrategy,
  nameFixReservedWordStrategy: APP_DEFAULTS.nameFix.reservedWordStrategy,
  nameFixLengthOverflowStrategy: APP_DEFAULTS.nameFix.lengthOverflowStrategy,
  nameFixMaxIdentifierLength: APP_DEFAULTS.nameFix.maxIdentifierLength,
  nameFixBackupRetentionDays: APP_DEFAULTS.nameFix.backupRetentionDays,
  nameFixMaxBatchConcurrency: APP_DEFAULTS.nameFix.maxBatchConcurrency,
  allowOverwriteInElectron: APP_DEFAULTS.nameFix.allowOverwriteInElectron,
  allowExternalPathWrite: APP_DEFAULTS.nameFix.allowExternalPathWrite,
} as const;

export function createDefaultDdlSettings() {
  return {
    ...DEFAULT_DDL_SETTINGS_VALUES,
    pkMarkers: [...DEFAULT_DDL_SETTINGS_VALUES.pkMarkers],
    downloadPath: undefined,
    excelReadPath: undefined,
    customHeaderTemplate: undefined,
  };
}

