export const HTTP_STATUS = {
  OK: 200,
  CREATED: 201,
  BAD_REQUEST: 400,
  FORBIDDEN: 403,
  NOT_FOUND: 404,
  PAYLOAD_TOO_LARGE: 413,
  TOO_MANY_REQUESTS: 429,
  INTERNAL_SERVER_ERROR: 500,
  SERVICE_UNAVAILABLE: 503,
} as const;

export const API_RESPONSE_MESSAGES = {
  serviceBusy: "Service is temporarily busy. Please retry shortly.",
  tooManyUploads: "Too many uploads. Please retry later.",
  tooManyParses: "Too many parse requests. Please retry later.",
  taskQueueBusy: "Task queue is busy. Please retry shortly.",
  noFileUploaded: "No file uploaded",
  excelValidationFailed: "Uploaded file failed Excel validation",
  invalidExcelWorkbook: "Uploaded file is not a valid Excel workbook",
  uploadTaskScheduleFailed: "Failed to schedule upload processing task",
  fileNotFound: "File not found",
  fileDeleted: "File deleted",
  fileDeleteFailed: "Failed to delete file",
  excelParserBusy: "Excel parser is busy. Please retry shortly.",
  readExcelFailed: "Failed to read Excel file",
  sheetNameRequired: "Sheet name is required",
  taskNotFound: "Task not found",
  searchIndexFailed: "Failed to generate search index",
  ddlGenerateFailed: "Failed to generate DDL",
  zipGenerateFailed: "Failed to generate ZIP",
  downloadTokenRequired: "Download token is required.",
  settingsGetFailed: "Failed to get settings",
  settingsUpdateFailed: "Failed to update settings",
  externalPathWriteRestricted: "allowExternalPathWrite can only be enabled in local Electron mode.",
  diffPreviewFailed: "Failed to preview schema diff",
  diffConfirmFailed: "Failed to confirm rename suggestions",
  diffHistoryFailed: "Failed to load diff history",
  diffAlterPreviewFailed: "Failed to preview alter SQL",
  diffAlterExportFailed: "Failed to export alter SQL",
  diffNotFound: "Diff result not found",
} as const;

export const API_ERROR_CODES = {
  requestFailed: "REQUEST_FAILED",
  invalidRequest: "INVALID_REQUEST",
  noFileUploaded: "NO_FILE_UPLOADED",
  fileNotFound: "FILE_NOT_FOUND",
  readExcelFailed: "READ_EXCEL_FAILED",
  internalServerError: "INTERNAL_SERVER_ERROR",
  fileDeleteFailed: "FILE_DELETE_FAILED",
  readSheetFailed: "READ_SHEET_FAILED",
  parseRegionFailed: "PARSE_REGION_FAILED",
  parseSheetFailed: "PARSE_SHEET_FAILED",
  taskNotFound: "TASK_NOT_FOUND",
  searchIndexFailed: "SEARCH_INDEX_FAILED",
  ddlGenerateFailed: "DDL_GENERATE_FAILED",
  zipGenerateFailed: "ZIP_GENERATE_FAILED",
  settingsGetFailed: "SETTINGS_GET_FAILED",
  settingsUpdateFailed: "SETTINGS_UPDATE_FAILED",
  diffPreviewFailed: "DIFF_PREVIEW_FAILED",
  diffConfirmFailed: "DIFF_CONFIRM_FAILED",
  diffHistoryFailed: "DIFF_HISTORY_FAILED",
  diffAlterPreviewFailed: "DIFF_ALTER_PREVIEW_FAILED",
  diffAlterExportFailed: "DIFF_ALTER_EXPORT_FAILED",
  diffNotFound: "DIFF_NOT_FOUND",
} as const;
